# Generated by Django 5.2.17 on 2026-09-30 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('obligacion', 'Obligación / Configuración'), ('credencial', 'Credencial de acceso'), ('tarea', 'Tarea'), ('pago', 'Pago / Honorario'), ('documento', 'Documento'), ('otro', 'Otro')], default='otro', max_length=24)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada de historial',
                'verbose_name_plural': 'entradas de historial',
                'ordering': ('-creado_en',),
            },
        ),
    ]
