# Generated by Django 5.2.17 on 2026-10-09 16:08

import django.db.models.deletion
from django.db import migrations, models


def clasificar_entradas_existentes(apps, schema_editor):
    EntradaHistorial = apps.get_model('historial', 'EntradaHistorial')
    EntradaHistorial.objects.filter(tipo_accion__in=('creacion', 'modificacion')).update(seccion='clientes')
    EntradaHistorial.objects.filter(tipo_accion='credencial').update(seccion='credenciales')
    EntradaHistorial.objects.filter(tipo_accion='pago').update(seccion='honorarios')


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_razon_social'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradahistorial',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='entradahistorial',
            name='seccion',
            field=models.CharField(choices=[('clientes', 'Clientes'), ('credenciales', 'Credenciales'), ('obligaciones', 'Obligaciones'), ('tareas', 'Tareas'), ('documentos', 'Documentos'), ('servicios', 'Servicios y trámites'), ('requerimientos', 'Requerimientos'), ('agenda', 'Agenda'), ('gastos', 'Gastos'), ('honorarios', 'Honorarios'), ('usuarios', 'Usuarios'), ('notificaciones', 'Notificaciones'), ('configuracion', 'Administración'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='entradahistorial',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='clientes.cliente'),
        ),
        migrations.RunPython(clasificar_entradas_existentes, migrations.RunPython.noop),
    ]
