# Generated by Django 5.2.17 on 2026-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_entradahistorial_referencia_entradahistorial_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradahistorial',
            name='seccion',
            field=models.CharField(choices=[('clientes', 'Clientes'), ('credenciales', 'Credenciales'), ('obligaciones', 'Obligaciones'), ('tareas', 'Tareas'), ('documentos', 'Documentos'), ('servicios', 'Servicios y trámites'), ('requerimientos', 'Requerimientos'), ('agenda', 'Agenda'), ('gastos', 'Gastos'), ('honorarios', 'Honorarios'), ('ingresos', 'Ingresos'), ('usuarios', 'Usuarios'), ('notificaciones', 'Notificaciones'), ('configuracion', 'Administración'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
