# Generated by Django 5.2.17 on 2026-09-30 18:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroHonorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_tipo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('extra', 'Servicio Extraordinario')], default='mensual', max_length=15)),
                ('anio', models.PositiveSmallIntegerField()),
                ('periodo_numero', models.PositiveSmallIntegerField(default=0, help_text='Mes (1-12) o Trimestre (1-4)')),
                ('concepto', models.CharField(max_length=200)),
                ('monto_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado'), ('cancelado', 'Anulado / Cancelado')], default='pendiente', max_length=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_honorarios', to='clientes.cliente')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honorarios_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cobro de honorario',
                'verbose_name_plural': 'cobros de honorarios',
                'ordering': ('-anio', '-periodo_numero', 'cliente__nombre'),
            },
        ),
        migrations.CreateModel(
            name='PagoHonorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('numero_recibo', models.CharField(blank=True, max_length=60)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia QR / Bancaria'), ('deposito', 'Depósito bancario'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('comprobante', models.FileField(blank=True, upload_to='comprobantes/pagos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='honorarios.cobrohonorario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_honorarios_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de honorario',
                'verbose_name_plural': 'pagos de honorarios',
                'ordering': ('-fecha_pago', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='TarifaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_trimestral', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_bancarizacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_gestora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_ministerio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_caja', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_otros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'tarifa de cliente',
                'verbose_name_plural': 'tarifas de clientes',
            },
        ),
    ]
