# Generated by Django 5.2.17 on 2026-10-09 12:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def clasificar_cobros_existentes(apps, schema_editor):
    CobroHonorario = apps.get_model('honorarios', 'CobroHonorario')
    CobroHonorario.objects.filter(periodo_tipo='extra').update(tipo_ingreso='extraordinario')


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrohonorario',
            name='tipo_ingreso',
            field=models.CharField(choices=[('recurrente', 'Recurrente'), ('extraordinario', 'Extraordinario')], default='recurrente', max_length=16),
        ),
        migrations.AddField(
            model_name='tarifacliente',
            name='extra_seprec',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='DetalleCobroHonorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('honorario', 'Honorario contable'), ('seprec', 'SEPREC'), ('ministerio', 'Ministerio'), ('caja', 'Caja'), ('gestora', 'Gestora'), ('licencia', 'Licencia'), ('tramite', 'Trámite'), ('certificado', 'Certificado'), ('otro', 'Otro')], max_length=16)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='honorarios.cobrohonorario')),
            ],
            options={
                'verbose_name': 'detalle de honorario',
                'verbose_name_plural': 'detalles de honorarios',
                'ordering': ('pk',),
            },
        ),
        migrations.RunPython(clasificar_cobros_existentes, migrations.RunPython.noop),
    ]
