# Generated by Django 5.2.17 on 2026-09-30 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoLaborable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'día no laborable',
                'verbose_name_plural': 'días no laborables',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='TipoObligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=12)),
                ('regla_vencimiento', models.CharField(choices=[('dia_fijo', 'Día fijo del mes siguiente'), ('digito_nit', 'Según terminación del NIT'), ('ultimo_habil', 'Último día hábil del mes siguiente'), ('cierre_fiscal_120', '120 días después del cierre fiscal'), ('manual', 'Fecha definida manualmente')], default='manual', max_length=20)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meses_despues_periodo', models.PositiveSmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de obligación',
                'verbose_name_plural': 'tipos de obligación',
                'ordering': ('periodicidad', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('periodo_numero', models.PositiveSmallIntegerField(default=0)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='clientes.cliente')),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligaciones_completadas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='obligaciones.tipoobligacion')),
            ],
            options={
                'verbose_name': 'obligación',
                'verbose_name_plural': 'obligaciones',
                'ordering': ('fecha_vencimiento', 'cliente__nombre', 'tipo__nombre'),
                'constraints': [models.UniqueConstraint(fields=('cliente', 'tipo', 'anio', 'periodo_numero'), name='obligacion_cliente_periodo_unico')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_obligaciones', to='clientes.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_clientes', to='obligaciones.tipoobligacion')),
            ],
            options={
                'verbose_name': 'configuración de obligación por cliente',
                'verbose_name_plural': 'configuraciones de obligaciones por cliente',
                'ordering': ('cliente__nombre', 'tipo__nombre'),
                'constraints': [models.UniqueConstraint(fields=('cliente', 'tipo'), name='obligacion_cliente_tipo_unico')],
            },
        ),
    ]
