# Generated by Django 5.2.17 on 2026-09-30 16:14

import apps.tareas.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligaciones', '0002_catalogo_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=8)),
                ('observaciones', models.TextField(blank=True)),
                ('evidencia', models.FileField(blank=True, upload_to='evidencias/tareas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg')), apps.tareas.models.validar_tamano_evidencia])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas_por_mi', to=settings.AUTH_USER_MODEL)),
                ('evidencia_subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_tareas_subidas', to=settings.AUTH_USER_MODEL)),
                ('obligacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarea', to='obligaciones.obligacion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ('obligacion__fecha_vencimiento', 'prioridad', 'obligacion__cliente__nombre'),
            },
        ),
    ]
