# Generated by Django 5.2.17 on 2026-10-09 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_razon_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='nuevo', max_length=16)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'requerimiento',
                'verbose_name_plural': 'requerimientos',
                'ordering': ('estado', 'fecha_limite', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='ComentarioRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_requerimientos', to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='requerimientos.requerimiento')),
            ],
            options={
                'verbose_name': 'comentario de requerimiento',
                'verbose_name_plural': 'comentarios de requerimientos',
                'ordering': ('creado_en', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ArchivoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='requerimientos/%Y/%m/')),
                ('nombre', models.CharField(max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_requerimientos_subidos', to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='requerimientos.requerimiento')),
            ],
            options={
                'verbose_name': 'archivo de requerimiento',
                'verbose_name_plural': 'archivos de requerimientos',
                'ordering': ('-subido_en',),
            },
        ),
    ]
