# Generated by Django 5.2.17 on 2026-09-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('persona_natural', 'Persona natural'), ('unipersonal', 'Empresa unipersonal'), ('juridica', 'Empresa jurídica')], default='persona_natural', max_length=20)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ci', models.CharField(blank=True, max_length=20)),
                ('actividad', models.CharField(choices=[('profesional', 'Profesional'), ('tecnico', 'Técnico'), ('alquiler', 'Alquiler'), ('comercial', 'Comercial'), ('servicios', 'Servicios'), ('industrial', 'Industrial'), ('constructora', 'Constructora'), ('agricola', 'Agrícola'), ('ganadera', 'Ganadera'), ('agroindustrial', 'Agroindustrial'), ('minera', 'Minera'), ('otra', 'Otra')], default='otra', max_length=24)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=240)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('nombre',),
            },
        ),
    ]
