# Generated by Django 5.2.17 on 2026-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cambio_contador_cliente_ci_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
