# Generated by Django 5.2.17 on 2026-10-09 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOcasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('documento', models.CharField(blank=True, default='', max_length=30)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=240)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_ocasionales_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente ocasional',
                'verbose_name_plural': 'clientes ocasionales',
                'ordering': ('nombre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ServicioTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licencia', 'Licencia'), ('tramite', 'Trámite'), ('certificado', 'Certificado'), ('otro', 'Otro')], default='tramite', max_length=16)),
                ('concepto', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_proceso', 'En proceso'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado')], default='nuevo', max_length=16)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.clienteocasional')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_ocasionales_registrados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_ocasionales_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servicio o trámite ocasional',
                'verbose_name_plural': 'servicios y trámites ocasionales',
                'ordering': ('-fecha_solicitud', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PagoServicioTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia QR / bancaria'), ('deposito', 'Depósito bancario'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('numero_recibo', models.CharField(blank=True, default='', max_length=60)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_servicios_ocasionales_registrados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='servicios.serviciotramite')),
            ],
            options={
                'verbose_name': 'pago de servicio ocasional',
                'verbose_name_plural': 'pagos de servicios ocasionales',
                'ordering': ('fecha_pago', 'pk'),
            },
        ),
    ]
