# Generated by Django 5.2.17 on 2026-09-30 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('impuestos', 'Impuestos Nacionales (SIAT)'), ('caja_salud', 'Caja de Salud (CNS/Otras)'), ('gestora', 'Gestora Pública'), ('ministerio', 'Ministerio de Trabajo (OVT)'), ('seprec', 'SEPREC'), ('banco', 'Banca / Portal Financiero'), ('otro', 'Otro sistema')], default='impuestos', max_length=24)),
                ('sistema_personalizado', models.CharField(blank=True, max_length=120)),
                ('usuario', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('codigo_extra', models.CharField(blank=True, help_text='PIN, tarjeta de coordenadas, correo vinculado u otro dato.', max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credenciales_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credenciales_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credencial',
                'verbose_name_plural': 'credenciales',
                'ordering': ('cliente__nombre', 'sistema', 'usuario'),
            },
        ),
    ]
