# Generated by Django 5.2.17 on 2026-09-28 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_perfiles_existentes(apps, schema_editor):
    Usuario = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    PerfilUsuario = apps.get_model('usuarios', 'PerfilUsuario')
    base_datos = schema_editor.connection.alias

    for usuario in Usuario.objects.using(base_datos).all().iterator():
        rol = 'administrador' if usuario.is_superuser else 'auxiliar'
        PerfilUsuario.objects.using(base_datos).get_or_create(
            usuario_id=usuario.pk,
            defaults={'rol': rol},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('auxiliar', 'Auxiliar'), ('secretario', 'Secretario')], default='auxiliar', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'ordering': ('usuario__username',),
            },
        ),
        migrations.RunPython(crear_perfiles_existentes, migrations.RunPython.noop),
    ]
