# Generated by Django 5.2.17 on 2026-10-08 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_razon_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('inversion', 'Inversión'), ('egreso', 'Egreso / salida')], max_length=16)),
                ('categoria', models.CharField(choices=[('alquiler', 'Alquiler de oficina'), ('sueldo_auxiliar', 'Sueldo de auxiliar'), ('sueldo_captadores', 'Sueldos de captadores'), ('sueldo_eeff', 'Sueldo extra EEFF'), ('firmas_auditoria', 'Firmas de auditoría'), ('aguinaldo', 'Aguinaldo'), ('internet', 'Internet'), ('luz', 'Luz'), ('refrigerio', 'Refrigerio'), ('pasajes', 'Pasajes'), ('suministros', 'Suministros de oficina'), ('impuestos', 'Impuestos'), ('facturas', 'Facturas'), ('talonarios', 'Talonarios'), ('pasanku', 'Pasanku'), ('sillas', 'Sillas'), ('monitor', 'Monitor'), ('escritorio', 'Escritorio'), ('computadora', 'Computadora'), ('impresora', 'Impresora'), ('muebles', 'Muebles y equipos'), ('otro', 'Otro')], max_length=24)),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('unico', 'Único'), ('extraordinario', 'Extraordinario')], default='unico', max_length=18)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('proveedor', models.CharField(blank=True, default='', max_length=180)),
                ('responsable', models.CharField(blank=True, default='', max_length=180)),
                ('comprobante', models.CharField(blank=True, default='', max_length=120)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado')], default='pendiente', max_length=12)),
                ('recuperable', models.BooleanField(default=False)),
                ('estado_recuperacion', models.CharField(choices=[('pendiente', 'Pendiente de recuperar'), ('recuperado', 'Recuperado')], default='pendiente', max_length=12)),
                ('vida_util_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado_activo', models.CharField(choices=[('en_uso', 'En uso'), ('baja', 'Dado de baja')], default='en_uso', max_length=8)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=180)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financieros', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financieros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro financiero',
                'verbose_name_plural': 'registros financieros',
                'ordering': ('-fecha', '-pk'),
            },
        ),
    ]
