# Generated by Django 5.2.17 on 2026-10-08 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_razon_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('cita', 'Cita'), ('recordatorio', 'Recordatorio')], default='cita', max_length=16)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=12)),
                ('lugar', models.CharField(blank=True, default='', max_length=160)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de agenda',
                'verbose_name_plural': 'eventos de agenda',
                'ordering': ('fecha', 'hora_inicio', 'titulo'),
            },
        ),
    ]
